/* This file generated by gen-fib.c - DO NOT EDIT. */

#pragma once
#include "gmp.h"

#if GMP_NUMB_BITS != 32
Error, error, this data is for 64 bits
#endif

#define FIB_TABLE_LIMIT 93
#define FIB_TABLE_LUCNUM_LIMIT 92
