/* Generated by           cobc 3.2.0 */
/* Generated from         ./src/kernel/MainCobol.cbl */
/* Generated at           May 15 2025 17:32:57 */
/* GnuCOBOL build date    May 15 2025 17:30:09 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        /opt/gnucobol-32bit/bin/cobc -o ./src/kernel/cobolTest/hello.c -C -O0 -std=cobol2002 ./src/kernel/MainCobol.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;
