/* Generated by           cobc 3.2.0 */
/* Generated from         ./src/kernel/MainCobol.cbl */
/* Generated at           May 15 2025 17:32:57 */
/* GnuCOBOL build date    May 15 2025 17:30:09 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        /opt/gnucobol-32bit/bin/cobc -o ./src/kernel/cobolTest/hello.c -C -O0 -std=cobol2002 ./src/kernel/MainCobol.cbl */

/* Program local variables for 'MainKernelInCobol' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];

